Add more debug for the upgrade task
Change-Id: I0b054345913e4a4528d3c37185f42b19ba36c44d

diff --git a/templates/major-upgrade-overcloud.sh.j2 b/templates/major-upgrade-overcloud.sh.j2
--- a/templates/major-upgrade-overcloud.sh.j2
+++ b/templates/major-upgrade-overcloud.sh.j2
@@ -104,3 +104,23 @@ openstack overcloud deploy --templates {{ tht_dir }} \
 
 echo "check upgrade status"
 heat stack-list | grep -i COMPLETE
+
+if heat stack-list | grep -q '_FAILED'; then
+
+    # get the failures list
+    openstack stack failures list overcloud > failed_upgrade_list.log || true
+
+    # get any puppet related errors
+    for failed in $(heat resource-list \
+        --nested-depth 5 overcloud | grep FAILED |
+        grep 'StructuredDeployment ' | cut -d '|' -f3)
+    do echo -n "heat deployment-show out put for deployment: $failed" >> failed_upgrade.log
+       echo -n "######################################################" >> failed_upgrade.log
+       heat deployment-show $failed >> failed_upgrade.log
+       echo -n "######################################################" >> failed_upgrade.log
+       echo "puppet standard error for deployment: $failed" >> failed_upgrade.log
+       echo -n "######################################################" >> failed_upgrade.log
+       echo -e $(heat deployment-show $failed | jq .output_values.deploy_stderr) >> failed_upgrade.log
+       echo -n "######################################################" >> failed_upgrade.log
+    done
+fi
